name: DeathLog
version: '${version}'
main: com.github.lukesky19.deathLog.DeathLog
api-version: '1.21'
depend: [SkyLib]

permissions:
    deathlog.command.deathlog:
        description: Base permission
        default: op
    deathlog.command.deathlog.restore:
        description: Permission to restore a player's inventory when they died.
        default: op
    deathlog.command.deathlog.give:
        description: Permission to give a player another a player's inventory when they died.
        default: op
    deathlog.command.deathlog.exp:
        description: Permission to restore a player's exp when they died.
        default: op
    deathlog.command.deathlog.info:
        description: Permission to view a player's deaths.
        default: op